### PR TITLE
Add Buffer support

### PR DESCRIPTION
**Pull request by chiro-hiro**
Add Buffer support, it may help developer more easy to working with this package.

### CODE REVIEW

**Comment by chiro-hiro** [comment]
Anyone there?

**Comment by jprichardson** [comment]
Thanks. Would you be willing to add tests?

**Comment by chiro-hiro** [comment]
@jprichardson Ok, thank you. Test have been updated, travis is updated as well.

**Comment by chiro-hiro** [comment]
@jprichardson Please take a look ;).

**Comment by fanatid** [comment]
@tad88dev I'm afraid this projects is not actual now in favor of [crypto-browserify/browserify-aes](https://github.com/crypto-browserify/browserify-aes)
I'm sorry that did not write about this before

**Pull request closed without merging**
